const express = require("express");
const { AdminController } = require("../controllers/admin.controller");
const router = express.Router();
let admin = new AdminController();
router.route("/menu").get(admin.index);
router.route("/class-detail/:id").get(admin.classDetail).post(admin.classDetail);
router.route("/class-detail/:id/cancel").get(admin.cancelClass);
router.route("/new-class-management/appove").post(admin.approveNewClass);
router.route("/new-class-management/cancel").post(admin.cancelNewClass);
router.route("/new-class-management").get(admin.newClassManagement);
router.route("/class-in-the-process").get(admin.classInReviewRrocessManagement);
router.route("/class-management").get(admin.classManagement);
router.route("/employee-management").get(admin.employeeManagement);
router.route("/user-management").get(admin.userManagement);
router.route("/approve-tutor/:id").get(admin.approveNewTutor);
router.route("/approving-tutor-management").get(admin.aprovingTutorManagement);
router.route("/tutor-management").get(admin.tutorManagement);
router.route("/course-documents/:courseId").get(admin.viewDocument);
router.route("/tutor/remove").post(admin.tutorConfirmDelete);
router.route("/tutor-remove").post(admin.deleteTutor);
router.route("/tutor-detail/:id").get(admin.tutorDetail);
router.route("/tuition-management").get(admin.tuitionManagement);
router.route("/tuition/update").post(admin.updateTuitionHandler);
router.route("/class-management").get(admin.classManagement);
router.route("/post-management").get(admin.postManagement).post(admin.postManagement);
router.route("/post/new-post").post(admin.newPost);
router.route("/evaluate").get(admin.evaluate);
router.get("/files-manager/:folder", admin.manageFile);
router.route("/").get(admin.index);
module.exports = router;
